# Generated by Django 5.0.3 on 2024-12-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_availability_alter_package_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(help_text='Duration in days'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/packages'),
        ),
    ]
