# Generated by Django 5.1.2 on 2024-11-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('hotel_owner', 'Hotel Owner'), ('activity_lister', 'Activity Lister')], default='admin', max_length=20),
        ),
    ]
