# Generated by Django 5.0.3 on 2024-12-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_fullname_booking_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fullname',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
